// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#pragma once
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

// SECRET_DEVICE_KEY;    // Secret device password

CloudTelevision projector;




