// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5038539c-82b5-482c-bf5d-d99062cd1916";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onXGIMIRemorePairChange();
void onXGIMIProjectorChange();

CloudSwitch xGIMI_Remore_Pair;
CloudTelevision xGIMI_projector;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(xGIMI_Remore_Pair, READWRITE, ON_CHANGE, onXGIMIRemorePairChange);
  ArduinoCloud.addProperty(xGIMI_projector, READWRITE, ON_CHANGE, onXGIMIProjectorChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);